### PR TITLE
build and release for all os

### PR DESCRIPTION
**Pull request by Roms1383**
Build for each platform and add all the resulting binaries to GH release.

⚠️ This PR is tighly coupled to jac3km4/redscript-ide-vscode#7.

### CODE REVIEW

**Comment by jac3km4** [comment]
@Roms1383 
there seem to be 2 issues with the job:
- the non-windows job moves the exe to the current directory and then tries to upload it from the target dir, so the upload actually uploads nothing
  - `Warning: No files were found with the provided path: target/release/redscript-ide-macos-silicon. No artifacts will be uploaded.`
- this if condition doesn't work `${{ inputs.artifact != 'windows-latest'}}`

**Comment by jac3km4** [comment]
@Roms1383 looks like `Rename-Item` is now being used incorrectly, I think you can change the `NewName` to just filename

**Comment by Roms1383** [comment]
as for `Rename-Item`, that's literally [the first example from their documentation ](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/rename-item?view=powershell-7.4#example-1-rename-a-file)... 😅

**Comment by Roms1383** [comment]
Ok my bad I didn't read thoroughly, let's see now.

**Comment by Roms1383** [comment]
Do you want me to rename the conditional job step for better readability @jac3km4 ?

**Pull request merged**
